### ISSUE TITLE
Getting error Exception in thread "main" java.lang.NullPointerException

### ISSUE THREAD

**Issue by vinaysikarwar** [troublediehard/magento-react-native#14]
Exception in thread "main" java.lang.NullPointerException
        at org.gradle.wrapper.BootstrapMainStarter.findLauncherJar(BootstrapMainStarter.java:34)
        at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:25)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:127)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)

**Comment by vinaysikarwar** [comment]
Can you please tell what java version is supported in this

**Comment by troublediehard** [comment]
@vinaysikarwar it is same java version as React Native v0.56. I didn't find official docs but in most cases, it recommended use Java 8. 

Can you please describe what are you trying to do? provide steps to reproduce the following issue?

**Comment by vinaysikarwar** [comment]
I have used Java version 8 and react native latest version.

I am just trying to setup this repo with our Magento version.

But it is throwing error

**Comment by troublediehard** [comment]
@vinaysikarwar so can provide details what are you doing? Like 
1. Download repository
2. run `npm install`
3. run react-native link
...

etc
from start to the point where you are getting the error.

**Comment by vinaysikarwar** [comment]
OK installed everything from fresh and that error got resolved now. but error in app

1. git clone https://github.com/troublediehard/magento-react-native.git

2. npm install

3. Fresh install of java 
	C:\Program Files (x86)\Java\jdk1.8.0_181
	C:\Program Files (x86)\Java\jre1.8.0_181
	
4. react-native link react-native-vector-icons

5. copy src/config/magento-sample.js to src/config/magento.js

6. setting configuration in magento.js

7. react-native run-android for android
	 throws error
	 => * What went wrong:
			A problem occurred configuring project ':app'.
			> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.
			
8. Created new file local.properties inside *android* folder with value as (sdk.dir = C:\\Program Files (x86)\\Java\\jdk1.8.0_181)

9.  again run (react-native run-android)
	throws error
	A problem occurred configuring project ':app'.
	=> You have not accepted the license agreements of the following SDK components:
	  [Android SDK Build-Tools 26.0.3, Android SDK Platform 26].
	  Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager.
	  Alternatively, to learn how to transfer the license agreements from one workstation to another, go to http://d.android.com/r/studio-ui/export-licenses.html
	  
9. Set sdk location to (sdk.dir = C:\\androidstudio) where my android studio is installed
 again executed command (react-native run-android)
 
10. adb is not recognised as internal or external command error.
	=> Installed adb and set path in environment variable using this link
		https://www.xda-developers.com/install-adb-windows-macos-linux/
		https://www.xda-developers.com/adb-fastboot-any-directory-windows-linux/
		
11. Everything worked perfectly but error in phone
	=> The development server returned response error code: 500
	URL: http://localhost:8081/index.delta?platform=android&dev=true&minify=false

**Comment by vinaysikarwar** [comment]
Loading dependency graph, done.
error: bundling failed: Error: Unable to resolve module `AccessibilityInfo` from `C:\ReactNative\mrn\node_modules\react-native\Libraries\react-native\react-native-implementation.js`: Module `AccessibilityInfo` does not exist in the Haste module map

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.  4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`.
    at ModuleResolver.resolveDependency (C:\ReactNative\mrn\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:167:1306)
    at ResolutionRequest.resolveDependency (C:\ReactNative\mrn\node_modules\metro\src\node-haste\DependencyGraph\ResolutionRequest.js:80:16)
    at DependencyGraph.resolveDependency (C:\ReactNative\mrn\node_modules\metro\src\node-haste\DependencyGraph.js:237:485)
    at Object.resolve (C:\ReactNative\mrn\node_modules\metro\src\lib\transformHelpers.js:116:25)
    at dependencies.map.result (C:\ReactNative\mrn\node_modules\metro\src\DeltaBundler\traverseDependencies.js:298:29)
    at Array.map (<anonymous>)
    at resolveDependencies (C:\ReactNative\mrn\node_modules\metro\src\DeltaBundler\traverseDependencies.js:294:16)
    at C:\ReactNative\mrn\node_modules\metro\src\DeltaBundler\traverseDependencies.js:159:33
    at Generator.next (<anonymous>)
    at step (C:\ReactNative\mrn\node_modules\metro\src\DeltaBundler\traverseDependencies.js:239:307)
 BUNDLE  [android, dev] ..\..\../index.js ░░░░░░░░░░░░░░░░ 0.0% (0/3), failed.

**Comment by troublediehard** [comment]
@vinaysikarwar do you have same error as here https://github.com/troublediehard/magento-react-native/issues/10#issuecomment-412743713 ?

Or like here https://github.com/troublediehard/magento-react-native/issues/13#issuecomment-420297904

**Comment by vinaysikarwar** [comment]
yes same issue. so do i downgrade to lower version

**Comment by troublediehard** [comment]
@vinaysikarwar yes, I think you can try either downgrade to 0.55 and upgrade to 0.57. I'm not using Windows can't say for sure is it resolve the issue.

**Comment by vinaysikarwar** [comment]
@troublediehard Thanks.

I upgraded to latest 0.57 but another error.
Loading dependency graph, done.
error: bundling failed: SyntaxError: C:\ReactNative\mrn\node_modules\react-native\Libraries\Image\Image.android.js: Support for the experimental syntax 'optionalChaining' isn't currently enabled (221:13):

  219 |   let style;
  220 |   let sources;
> 221 |   if (source?.uri != null) {
      |             ^
  222 |     /* $FlowFixMe(>=0.78.0 site=react_native_android_fb) This issue was found
  223 |      * when making Flow check .android.js files. */
  224 |     const {width, height} = source;

![image](https://user-images.githubusercontent.com/5436260/46293250-8b7de600-c5b0-11e8-9171-e17e5332ed92.png)

**Comment by troublediehard** [comment]
@vinaysikarwar can you share your `package.json` file?

**Comment by vinaysikarwar** [comment]
Please check the attached file . I am not sure why it requires bable core
module. after installing that also it gives optional chaining error and
also bable module are not stable that throws error.

**Comment by vinaysikarwar** [comment]
FResh install gives optional chaining error

Loading dependency graph, done.
 BUNDLE  [android, dev] ..\..\../index.js ▓▓▓▓▓▓▓▓▓▓░░░░░░ 64.3% (667/832)::ffff:127.0.0.1 - - [02/Oct/2018:04:30:46 +0000] "GET /index.delta?platform=android&dev=true&minify=false HTTP/1.1" 500 - "-" "okhttp/3.10.0"
error: bundling failed: SyntaxError: C:\ReactNative\mrn\node_modules\react-native\Libraries\Components\Switch\Switch.js: Support for the experimental syntax 'optionalChaining' isn't currently enabled (103:41):

  101 |     // Support deprecated color props.
  102 |     let _thumbColor = thumbColor;
> 103 |     let _trackColorForFalse = trackColor?.false;
      |                                         ^
  104 |     let _trackColorForTrue = trackColor?.true;
  105 |
  106 |     // TODO: Remove support for these props after a couple releases.

Add @babel/plugin-proposal-optional-chaining (https://git.io/vb4Sk) to the 'plugins' section of your Babel config to enable transformation.
    at _class.raise (C:\ReactNative\mrn\node_modules\@babel\parser\lib\index.js:3939:15)
    at _class.expectPlugin (C:\ReactNative\mrn\node_modules\@babel\parser\lib\index.js:5253:18)
    at _class.parseSubscript (C:\ReactNative\mrn\node_modules\@babel\parser\lib\index.js:5959:12)
    at _class.parseSubscript (C:\ReactNative\mrn\node_modules\@babel\parser\lib\index.js:2716:51)
    at _class.parseSubscripts (C:\ReactNative\mrn\node_modules\@babel\parser\lib\index.js:5944:19)
    at _class.parseSubscripts (C:\ReactNative\mrn\node_modules\@babel\parser\lib\index.js:2669:52)
    at _class.parseExprSubscripts (C:\ReactNative\mrn\node_modules\@babel\parser\lib\index.js:5934:17)
    at _class.parseMaybeUnary (C:\ReactNative\mrn\node_modules\@babel\parser\lib\index.js:5903:21)
    at _class.parseExprOps (C:\ReactNative\mrn\node_modules\@babel\parser\lib\index.js:5812:21)
    at _class.parseMaybeConditional (C:\ReactNative\mrn\node_modules\@babel\parser\lib\index.js:5784:21)
 BUNDLE  [android, dev] ..\..\../index.js ▓▓▓▓▓▓▓▓▓▓▓▓░░░░ 77.5% (752/854), failed.

**Comment by vinaysikarwar** [comment]
Optional chaining error resolved by updating the .babelrc file like below.

`{
  "plugins": [
	"@babel/plugin-proposal-optional-chaining"
  ],
  "presets": [
	"react-native"
  ]
}`

**Comment by vinaysikarwar** [comment]
but then there is new error 

Loading dependency graph, done.
 BUNDLE  [android, dev] ..\..\../index.js ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░ 99.1% (850/854)::ffff:127.0.0.1 - - [02/Oct/2018:06:27:41 +0000] "GET /index.delta?platform=android&dev=true&minify=false HTTP/1.1" 500 - "-" "okhttp/3.10.0"
error: bundling failed: TypeError: Cannot read property 'bindings' of null
    at Scope.moveBindingTo (c:\ReactNative\mrn\node_modules\@babel\traverse\lib\scope\index.js:867:13)
    at BlockScoping.updateScopeInfo (c:\ReactNative\mrn\node_modules\babel-plugin-transform-es2015-block-scoping\lib\index.js:364:17)
    at BlockScoping.run (c:\ReactNative\mrn\node_modules\babel-plugin-transform-es2015-block-scoping\lib\index.js:330:12)
    at PluginPass.BlockStatementSwitchStatementProgram (c:\ReactNative\mrn\node_modules\babel-plugin-transform-es2015-block-scoping\lib\index.js:70:24)
    at newFn (c:\ReactNative\mrn\node_modules\@babel\traverse\lib\visitors.js:193:21)
    at NodePath._call (c:\ReactNative\mrn\node_modules\@babel\traverse\lib\path\context.js:53:20)
    at NodePath.call (c:\ReactNative\mrn\node_modules\@babel\traverse\lib\path\context.js:40:17)
    at NodePath.visit (c:\ReactNative\mrn\node_modules\@babel\traverse\lib\path\context.js:88:12)
    at TraversalContext.visitQueue (c:\ReactNative\mrn\node_modules\@babel\traverse\lib\context.js:118:16)
 BUNDLE  [android, dev] ..\..\../index.js ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░ 99.1% (850/854), failed.

**Comment by troublediehard** [comment]
Can you join my Slack workspace? Send me your email to troublesohard@gmail.com

**Comment by vinaysikarwar** [comment]
Finally all issues are resolved and I will share the guidelines to follow to setup it in windows

**Comment by vinaysikarwar** [comment]
But I am not sure if things are working as you have shown the demo. At my ends nothing loading fine in app. shows all categories link in home and no content on click. only loading icon

**Comment by troublediehard** [comment]
@vinaysikarwar glad to hear you resolved the issue. Rich me in Slack I'll explain to you how to configure app or why it works as expected.
